version : 2

sources :
  - name: raw
    database: soy-meridian-475010-m5
    schema: gz_raw_data
    loader: bigquery
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: product
        identifier: raw_gz_product
        description: product list with purchase cost associated
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
      - name: sales
        identifier: raw_gz_sales
        description: greenweez sales        
      - name: ship
        identifier: raw_gz_ship
        description: all ship cost or fee related to orders_id
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
models: 
  - name: stg_sales
    description: tables sales cleaned
    columns:
      - name: date_date
        description: date or purchase
      - name: prim_key
      - name: orders_id
      - name: products_id
      - name: revenue
      - name: quantity 


  

