version : 2

sources :
  - name: raw
    database: soy-meridian-475010-m5
    schema: gz_raw_data
    loader: bigquery
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: product
        identifier: raw_gz_product
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship
     
  

